[project]
name = "cse427-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nahin Munkar", email = "nahinmunkarnm@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
]

[project.scripts]
cse427-project = "cse427_project:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
